# generated by datamodel-codegen:
#   filename:  https://developer.kadaster.nl/schemas/kik-inzage/6.0.x/openapi.yaml
#   timestamp: 2023-06-13T13:07:05+00:00

from __future__ import annotations

from datetime import date
from datetime import datetime
from enum import Enum

from pydantic import AnyUrl
from pydantic import BaseModel
from pydantic import Field
from pydantic import RootModel


class AdresLocatieTypeEnum(Enum):
    OBJECTLOCATIE_BINNENLAND = "ObjectlocatieBinnenland"
    OBJECTLOCATIE_BUITENLAND = "ObjectlocatieBuitenland"
    POSTBUS_LOCATIE = "PostbusLocatie"


class Adresnummer(RootModel[str]):
    root: str = Field(..., title="Adresnummer")


class AppartementsrechtSplitsingTypeEnum(Enum):
    HOOFSPLITSING = "Hoofsplitsing"
    ONDERSPLITSING = "Ondersplitsing"
    SPIEGELSPLITSING_ONDERSPLITSING = "SpiegelsplitsingOndersplitsing"
    SPIEGELSPLITSING_AFKOOP_ERFPACHT = "SpiegelsplitsingAfkoopErfpacht"


class DatuminformatieProduct(BaseModel):
    actualiteitstijdstip_hypothecair: datetime | None = Field(
        None, alias="actualiteitstijdstipHypothecair"
    )
    actualiteitstijdstip_kadastraal: datetime | None = Field(
        None, alias="actualiteitstijdstipKadastraal"
    )
    klantreferentie: str | None = Field(None, title="klantreferentie")
    productieordernummer: str | None = Field(None, title="productieordernummer")
    signaleringstijdstip_beslagen: datetime | None = Field(
        None, alias="signaleringstijdstipBeslagen"
    )
    signaleringstijdstip_hypothecair: datetime | None = Field(
        None, alias="signaleringstijdstipHypothecair"
    )
    signaleringstijdstip_kadastraal: datetime | None = Field(
        None, alias="signaleringstijdstipKadastraal"
    )
    tijdstip_samenstelling_bericht: datetime | None = Field(
        None, alias="tijdstipSamenstellingBericht"
    )


class DownloadGegevens(BaseModel):
    download_url: str | None = Field(None, alias="downloadUrl")
    afgifte_id: str | None = Field(None, alias="afgifteId")


class Formaat(Enum):
    JSON = "json"
    PDF = "pdf"
    JSON_PDF = "json,pdf"
    PDF_JSON = "pdf,json"


class Foutbericht(BaseModel):
    type: AnyUrl | None = Field(
        None, description="Link naar meer informatie over deze fout"
    )
    title: str | None = Field(None, description="Beschrijving van de fout")
    status: int | None = Field(None, description="Http status code")
    detail: str | None = Field(None, description="Details over de fout")


class GeleverdProductBrondocument(BaseModel):
    product: DownloadGegevens | None = None
    authentieke_akte: DownloadGegevens | None = Field(None, alias="authentiekeAkte")


class GeleverdProductDatuminformatie(BaseModel):
    product: DatuminformatieProduct | None = None


class InvalidParam(BaseModel):
    type: AnyUrl | None = None
    name: str | None = Field(None, description="Naam van de parameter")
    reason: str | None = Field(
        None, description="Beschrijving van de fout op de parameterwaarde"
    )


class SeverityCode(Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    FATAL = "FATAL"


class Melding(BaseModel):
    code: str | None = None
    omschrijving: str | None = None
    severity_code: SeverityCode | None = Field(None, alias="severityCode")


class MeldingProduct(BaseModel):
    nummer: str | None = None
    tekst: str | None = None


class Naam(BaseModel):
    geslachtsnaam: str | None = Field(None, max_length=200, min_length=1)
    voornamen: str | None = Field(None, max_length=200, min_length=1)
    voorvoegselsgeslachtsnaam: str | None = Field(None, max_length=10, min_length=1)


class NegatieveMededelingProduct(BaseModel):
    actualiteitstijdstip_hypothecair: datetime | None = Field(
        None, alias="actualiteitstijdstipHypothecair"
    )
    actualiteitstijdstip_kadastraal: datetime | None = Field(
        None, alias="actualiteitstijdstipKadastraal"
    )
    klantreferentie: str | None = Field(None, title="klantreferentie")
    melding_negatieve_mededeling: str | None = Field(
        None, alias="meldingNegatieveMededeling"
    )
    productieordernummer: str | None = Field(None, title="productieordernummer")
    signaleringstijdstip_beslagen: datetime | None = Field(
        None, alias="signaleringstijdstipBeslagen"
    )
    signaleringstijdstip_hypothecair: datetime | None = Field(
        None, alias="signaleringstijdstipHypothecair"
    )
    signaleringstijdstip_kadastraal: datetime | None = Field(
        None, alias="signaleringstijdstipKadastraal"
    )
    tijdstip_samenstelling_bericht: datetime | None = Field(
        None, alias="tijdstipSamenstellingBericht"
    )


class NEN3610ID(BaseModel):
    lokaal_id: str = Field(..., alias="lokaalID")
    namespace: str


class ObjectReferentieType(Enum):
    BAG = "BAG"
    BGT = "BGT"


class OnroerendeZaakBeperking(BaseModel):
    in_onderzoek: bool | None = Field(None, alias="inOnderzoek")
    beperkt: NEN3610ID | None = None


class OnroerendeZaakFiliatie(BaseModel):
    betreft_oz: NEN3610ID | None = Field(None, alias="betreftOZ")


class OnroerendeZaakTypeEnum(Enum):
    PERCEEL = "Perceel"
    APPARTEMENTSRECHT = "Appartementsrecht"
    LEIDINGNETWERK = "Leidingnetwerk"


class OpenbareRuimte(BaseModel):
    openbare_ruimte_naam: str | None = Field(
        None, alias="openbareRuimteNaam", max_length=80, min_length=1
    )
    gerelateerde_woonplaats_naam: str | None = Field(
        None, alias="gerelateerdeWoonplaatsNaam", max_length=80, min_length=1
    )


class OverigBetrokkenKadastraalObject(BaseModel):
    betreft: NEN3610ID | None = None
    heeft: NEN3610ID | None = None


class PersoonTypeEnum(Enum):
    NATUURLIJK_PERSOON = "NatuurlijkPersoon"
    NIET_NATUURLIJK_PERSOON = "NietNatuurlijkPersoon"


class Type(Enum):
    POINT = "Point"


class PointGeoJSON(BaseModel):
    type: Type
    coordinates: list[float] = Field(..., min_items=2)


class ProcesVerwerking(BaseModel):
    proces_verwerkingscode: int | None = Field(None, alias="procesVerwerkingscode")
    severity_code: SeverityCode | None = Field(None, alias="severityCode")
    meldingen: list[Melding] | None = None


class ProductGegevens(BaseModel):
    klantreferentie: str | None = None
    productieordernummer: str | None = None
    tijdstip_samenstelling_bericht: datetime | None = Field(
        None, alias="tijdstipSamenstellingBericht"
    )
    aantal_kadastrale_objecten: int | None = Field(
        None, alias="aantalKadastraleObjecten"
    )
    aanvraag_gegevens: str | None = Field(None, alias="aanvraagGegevens")
    meldingen_product: list[MeldingProduct] | None = Field(
        None, alias="meldingenProduct"
    )


class Product(BaseModel):
    actualiteitstijdstip_hypothecair: datetime | None = Field(
        None, alias="actualiteitstijdstipHypothecair"
    )
    actualiteitstijdstip_kadastraal: datetime | None = Field(
        None, alias="actualiteitstijdstipKadastraal"
    )
    klantreferentie: str | None = Field(None, title="klantreferentie")
    productieordernummer: str | None = Field(None, title="productieordernummer")
    signaleringstijdstip_beslagen: datetime | None = Field(
        None, alias="signaleringstijdstipBeslagen"
    )
    signaleringstijdstip_hypothecair: datetime | None = Field(
        None, alias="signaleringstijdstipHypothecair"
    )
    signaleringstijdstip_kadastraal: datetime | None = Field(
        None, alias="signaleringstijdstipKadastraal"
    )
    tijdstip_samenstelling_bericht: datetime | None = Field(
        None, alias="tijdstipSamenstellingBericht"
    )
    betreft: NEN3610ID | None = None


class Rechtspersoon(BaseModel):
    kvk_nummer: str | None = Field(None, alias="kvkNummer", max_length=8)


class SignaleringKadastraalObject(BaseModel):
    ten_behoeve_van: list[NEN3610ID] | None = Field(None, alias="tenBehoeveVan")
    van: NEN3610ID | None = None


class SignaleringPersoon(BaseModel):
    ten_behoeve_van: list[NEN3610ID] | None = Field(None, alias="tenBehoeveVan")
    van: NEN3610ID | None = None


class StukTypeEnum(Enum):
    TER_INSCHRIJVING_AANGEBODEN_STUK = "TerInschrijvingAangebodenStuk"
    KADASTERSTUK = "Kadasterstuk"


class Tijdstip(BaseModel):
    datum: date
    tijd: datetime


class TypeBreuk(BaseModel):
    noemer: int | None = None
    teller: int | None = None


class TypeOnvolledigeDatum(BaseModel):
    dag: int | None = Field(None, ge=1, le=31)
    datum: date | None = None
    jaar: int | None = Field(None, le=9999)
    maand: int | None = Field(None, ge=1, le=12)


class TypePostcode(RootModel[str]):
    root: str = Field(..., title="TypePostcode")


class Verblijfsobject(BaseModel):
    identificatie: str | None = None
    hoofdadres: NEN3610ID | None = None


class VerkavelObject(BaseModel):
    betreft: NEN3610ID | None = None
    ligt_in: NEN3610ID | None = Field(None, alias="ligtIn")


class VoorwaartseOnroerendeZaakFiliatie(BaseModel):
    betreft_oz: NEN3610ID | None = Field(None, alias="betreftOZ")


class Waardelijst(BaseModel):
    code: str
    waarde: str | None = None


class ZakelijkRecht(BaseModel):
    identificatie: NEN3610ID | None = None
    aard: Waardelijst | None = None
    toelichting_bewaarder: str | None = Field(None, alias="toelichtingBewaarder")
    is_gebaseerd_op: list[NEN3610ID] | None = Field(
        None, alias="isGebaseerdOp", min_items=0
    )
    is_vermeld_in: list[NEN3610ID] | None = Field(
        None, alias="isVermeldIn", min_items=0
    )
    rust_op: NEN3610ID | None = Field(None, alias="rustOp")
    is_belast_met: list[NEN3610ID] | None = Field(
        None, alias="isBelastMet", min_items=0
    )
    is_ontstaan_uit: NEN3610ID | None = Field(None, alias="isOntstaanUit")
    is_bestemd_tot: NEN3610ID | None = Field(None, alias="isBestemdTot")
    is_betrokken_bij: NEN3610ID | None = Field(None, alias="isBetrokkenBij")
    is_beperkt_tot: list[NEN3610ID] | None = Field(
        None, alias="isBeperktTot", min_items=0
    )


class ZekerheidsstellingTypeEnum(Enum):
    ZEKERHEIDSSTELLING_HYPOTHECAIR = "ZekerheidsstellingHypothecair"
    ZEKERHEIDSSTELLING_INZAKE_BESLAG = "ZekerheidsstellingInzakeBeslag"


class FieldAdresLocatie(BaseModel):
    identificatie: NEN3610ID | None = None
    type: AdresLocatieTypeEnum | None = None


class FieldKadastraalObject(BaseModel):
    identificatie: NEN3610ID | None = None


class FieldPersoon(BaseModel):
    identificatie: NEN3610ID | None = None
    type: PersoonTypeEnum | None = None
    beschikkingsbevoegdheid: Waardelijst | None = None
    indicatie_niet_toonbare_diakriet: bool | None = Field(
        None, alias="indicatieNietToonbareDiakriet"
    )
    postlocatie: NEN3610ID | None = None
    woonlocatie: NEN3610ID | None = None
    is_vermeld_in: list[NEN3610ID] | None = Field(
        None, alias="isVermeldIn", min_items=0
    )
    is_rechthebbende_van: list[NEN3610ID] | None = Field(
        None, alias="isRechthebbendeVan", min_items=0
    )
    is_betrokkene_bij: list[NEN3610ID] | None = Field(
        None, alias="isBetrokkeneBij", min_items=0
    )


class FieldStuk(BaseModel):
    identificatie: NEN3610ID | None = None
    type: StukTypeEnum | None = None
    toelichting_bewaarder: str | None = Field(None, alias="toelichtingBewaarder")
    omvat: list[NEN3610ID] | None = None


class FieldZekerheidsstelling(BaseModel):
    identificatie: NEN3610ID | None = None
    type: ZekerheidsstellingTypeEnum | None = None
    omschrijving_betrokken_recht: Waardelijst | None = Field(
        None, alias="omschrijvingBetrokkenRecht"
    )
    toelichting_bewaarder: str | None = Field(None, alias="toelichtingBewaarder")
    is_gebaseerd_op: NEN3610ID | None = Field(None, alias="isGebaseerdOp")
    is_vermeld_in: list[NEN3610ID] | None = Field(
        None, alias="isVermeldIn", min_items=0
    )
    rust_op_object: NEN3610ID | None = Field(None, alias="rustOpObject")
    heeft: list[NEN3610ID] | None = None
    heeft_meer_overig_betrokken_kadastraal_objecten: bool | None = Field(
        None, alias="heeftMeerOverigBetrokkenKadastraalObjecten"
    )


class Aantekening(BaseModel):
    identificatie: NEN3610ID | None = None
    aard: Waardelijst | None = None
    betreft_gedeelte_van_perceel: bool | None = Field(
        None, alias="betreftGedeelteVanPerceel"
    )
    einddatum: datetime | None = None
    einddatum_recht: datetime | None = Field(None, alias="einddatumRecht")
    omschrijving: str | None = None
    aantekening_kadastraal_object: NEN3610ID | None = Field(
        None, alias="aantekeningKadastraalObject"
    )
    aantekening_recht: list[NEN3610ID] | None = Field(
        None, alias="aantekeningRecht", min_items=0
    )
    is_vermeld_in: list[NEN3610ID] | None = Field(
        None, alias="isVermeldIn", min_items=0
    )
    is_gebaseerd_op: NEN3610ID | None = Field(None, alias="isGebaseerdOp")
    betrokken_persoon: list[NEN3610ID] | None = Field(
        None, alias="betrokkenPersoon", min_items=0
    )


class AanvullendeGegevens(BaseModel):
    bij_identificatie: NEN3610ID | None = Field(None, alias="bijIdentificatie")
    soort: str | None = None
    gegevens: str | None = None


class AdresBuitenland(BaseModel):
    adres: str | None = Field(None, max_length=50, min_length=1)
    identificatie: Adresnummer | None = None
    land: Waardelijst | None = None
    regio: str | None = Field(None, max_length=39, min_length=1)
    woonplaats: str | None = Field(None, max_length=80, min_length=1)


class AppartementsrechtSplitsing(BaseModel):
    identificatie: NEN3610ID | None = None
    type: AppartementsrechtSplitsingTypeEnum | None = None
    is_vermeld_in: list[NEN3610ID] | None = Field(
        None, alias="isVermeldIn", min_items=0
    )
    heeft_vereniging_van_eigenaren: NEN3610ID | None = Field(
        None, alias="heeftVerenigingVanEigenaren"
    )
    is_gebaseerd_op: NEN3610ID | None = Field(None, alias="isGebaseerdOp")


class AttenderingKadastraalObject(BaseModel):
    van: NEN3610ID | None = None
    ten_behoeve_van: list[NEN3610ID] | None = Field(
        None, alias="tenBehoeveVan", title="tenBehoeveVan"
    )


class AttenderingPersoon(BaseModel):
    van: NEN3610ID | None = None
    ten_behoeve_van: list[NEN3610ID] | None = Field(
        None, alias="tenBehoeveVan", title="tenBehoeveVan"
    )


class Bedrag(BaseModel):
    som: float | None = None
    valuta: Waardelijst | None = None


class Brondocument(BaseModel):
    proces: ProcesVerwerking | None = None
    product_gegevens: ProductGegevens | None = Field(None, alias="productGegevens")
    geleverd_product: GeleverdProductBrondocument | None = Field(
        None, alias="geleverdProduct"
    )


class BsnBody(BaseModel):
    burgerservicenummer: str = Field(..., pattern="^([0][0-9]{8})|([1-9][0-9]{7,8})$")
    formaat: Formaat
    klantreferentie: str = Field(..., max_length=20, min_length=3)
    gebruikeridentificatie: str | None = Field(None, max_length=20)
    hyperlinkopproduct: bool | None = None
    inkoopnummer: str | None = Field(None, max_length=35)
    referentienummer: str | None = Field(None, max_length=35)


class Datuminformatie(BaseModel):
    proces: ProcesVerwerking | None = None
    product_gegevens: ProductGegevens | None = Field(None, alias="productGegevens")
    geleverd_product: GeleverdProductDatuminformatie | None = Field(
        None, alias="geleverdProduct"
    )


class FoutberichtBadRequest(Foutbericht):
    invalid_params: list[InvalidParam] | None = Field(
        None,
        alias="invalidParams",
        description="Foutmelding per fout in een parameter. Alle gevonden fouten worden één keer teruggemeld.",
    )


class Geboorte(BaseModel):
    geboortedatum: TypeOnvolledigeDatum | None = None
    geboorteland: Waardelijst | None = None
    geboorteplaats: str | None = Field(None, max_length=80, min_length=1)


class GeleverdProductKadastraalPersoonIdentificatie(BaseModel):
    negatieve_mededeling: NegatieveMededelingProduct | None = Field(
        None, alias="negatieveMededeling"
    )
    product: NEN3610ID | None = None


class Geslacht(BaseModel):
    geslachtsaanduiding: Waardelijst | None = None


class GevraagdGebied(BaseModel):
    betreft_onroerende_zaken: list[NEN3610ID] | None = Field(
        None, alias="betreftOnroerendeZaken"
    )
    huisletter: str | None = Field(None, pattern="^[a-zA-Z]$")
    huisnummer: int | None = Field(None, ge=1, le=99999)
    huisnummertoevoeging: str | None = Field(None, pattern="^([a-z,A-Z,0-9]){1,4}$")
    identificatie: NEN3610ID | None = None
    postcode: str | None = Field(None, pattern="^[1-9][0-9][0-9][0-9][A-Z][A-Z]$")
    straatnaam: str | None = Field(None, max_length=80)
    plaatsnaam: str | None = Field(None, max_length=80)


class GezamenlijkAandeel(BaseModel):
    identificatie: NEN3610ID | None = None
    aandeel: TypeBreuk | None = None


class Herverkavelingsgebied(BaseModel):
    identificatie: NEN3610ID | None = None
    status_herverkavelingsproject: Waardelijst | None = Field(
        None, alias="statusHerverkavelingsproject"
    )


class JaarlijksBedrag(BaseModel):
    bedrag: Bedrag | None = None
    betreft_meer_onroerende_zaken: bool | None = Field(
        None, alias="betreftMeerOnroerendeZaken"
    )


class KadastraalPersoonIdentificatie(BaseModel):
    proces: ProcesVerwerking | None = None
    product_gegevens: ProductGegevens | None = Field(None, alias="productGegevens")
    geleverd_product: NEN3610ID | None = Field(None, alias="geleverdProduct")
    geleverd_product_kpi: None | (
        GeleverdProductKadastraalPersoonIdentificatie
    ) = Field(None, alias="geleverdProductKPI")


class LocatieKadastraalObject(BaseModel):
    koppelingswijze: Waardelijst | None = None
    betreft: NEN3610ID | None = None
    heeft: NEN3610ID | None = None


class Mandeligheid(BaseModel):
    identificatie: NEN3610ID | None = None
    is_vermeld_in: list[NEN3610ID] | None = Field(
        None, alias="isVermeldIn", min_items=0
    )
    is_gebaseerd_op: list[NEN3610ID] | None = Field(None, alias="isGebaseerdOp")
    heeft_hoofdzaak: list[NEN3610ID] | None = Field(None, alias="heeftHoofdzaak")


class NietNatuurlijkPersoon(FieldPersoon):
    rechtsvorm: Waardelijst | None = None
    statutaire_naam: str | None = Field(
        None, alias="statutaireNaam", max_length=200, min_length=1
    )
    statutaire_zetel: str | None = Field(
        None, alias="statutaireZetel", max_length=40, min_length=1
    )
    betreft: Rechtspersoon | None = None


class Nummeraanduiding(BaseModel):
    huisletter: str | None = Field(None, max_length=1, pattern="[a-zA-Z]")
    huisnummer: int | None = Field(None, max_length=5, min_length=1)
    huisnummertoevoeging: str | None = Field(
        None, max_length=4, min_length=1, pattern="([a-z,A-Z,0-9])+"
    )
    identificatie: str | None = None
    postcode: str | None = Field(
        None, max_length=6, pattern="[1-9][0-9][0-9][0-9][A-Z][A-Z]"
    )
    gerelateerde_openbare_ruimte: OpenbareRuimte | None = Field(
        None, alias="gerelateerdeOpenbareRuimte"
    )
    gerelateerde_woonplaats_naam: str | None = Field(
        None, alias="gerelateerdeWoonplaatsNaam", max_length=80, min_length=1
    )


class ObjectlocatieBinnenland(FieldAdresLocatie):
    nummeraanduiding: Nummeraanduiding | None = None


class ObjectlocatieBuitenland(FieldAdresLocatie):
    adres_buitenland: AdresBuitenland | None = Field(None, alias="adresBuitenland")


class ObjectReferentie(BaseModel):
    type: ObjectReferentieType | None = None
    domein: str | None = None
    identificatie_referentie: str | None = Field(None, alias="identificatieReferentie")


class Overlijden(BaseModel):
    datum_overlijden: TypeOnvolledigeDatum | None = Field(None, alias="datumOverlijden")


class PortefeuilleId(BaseModel):
    akr_registercode: Waardelijst | None = Field(None, alias="akrRegistercode")
    akr_stukdeel1: str | None = Field(None, alias="akrStukdeel1")
    akr_stukdeel2: str | None = Field(None, alias="akrStukdeel2")
    akr_stukdeel3: str | None = Field(None, alias="akrStukdeel3")
    volgnummer_staat75: int | None = Field(None, alias="volgnummerStaat75")


class PostbusLocatie(FieldAdresLocatie):
    postbusnummer: int | None = Field(None, max_length=7, min_length=1)
    postcode: TypePostcode | None = None
    woonplaats_naam: str | None = Field(
        None, alias="woonplaatsNaam", max_length=80, min_length=1
    )


class PubliekrechtelijkeBeperking(BaseModel):
    identificatie: NEN3610ID | None = None
    datum_beeindiging: datetime | None = Field(None, alias="datumBeeindiging")
    datum_in_werking: datetime | None = Field(None, alias="datumInWerking")
    grondslag: Waardelijst | None = None
    is_gebaseerd_op: NEN3610ID | None = Field(None, alias="isGebaseerdOp")
    is_vermeld_in: list[NEN3610ID] | None = Field(None, alias="isVermeldIn")
    leidt_tot: list[OnroerendeZaakBeperking] | None = Field(None, alias="leidtTot")
    bevoegd_gezag: NEN3610ID | None = Field(None, alias="bevoegdGezag")
    heeft: NEN3610ID | None = None


class Stukdeel(BaseModel):
    identificatie: NEN3610ID | None = None
    aard: Waardelijst | None = None
    datum_kenbaarheid_pb: datetime | None = Field(None, alias="datumKenbaarheidPB")
    omschrijving_gekozen_woonplaats: str | None = Field(
        None, alias="omschrijvingGekozenWoonplaats"
    )
    is_aanvulling_op: list[NEN3610ID] | None = Field(
        None, alias="isAanvullingOp", min_items=0
    )
    bedrag_vorderingsbeslag: Bedrag | None = Field(None, alias="bedragVorderingsbeslag")
    bedrag_zekerheidsstelling_hypotheek: Bedrag | None = Field(
        None, alias="bedragZekerheidsstellingHypotheek"
    )


class Tenaamstelling(BaseModel):
    identificatie: NEN3610ID | None = None
    aandeel: TypeBreuk | None = None
    burgerlijke_staat_ten_tijde_van_verkrijging: Waardelijst | None = Field(
        None, alias="burgerlijkeStaatTenTijdeVanVerkrijging"
    )
    omschrijving: str | None = Field(None, max_length=50, min_length=1)
    verkregen_namens_samenwerkingsverband: Waardelijst | None = Field(
        None, alias="verkregenNamensSamenwerkingsverband"
    )
    betrokken_partner: NEN3610ID | None = Field(None, alias="betrokkenPartner")
    geldt_voor: NEN3610ID | None = Field(None, alias="geldtVoor")
    is_vermeld_in: list[NEN3610ID] | None = Field(
        None, alias="isVermeldIn", min_items=0
    )
    betrokken_samenwerkingsverband: NEN3610ID | None = Field(
        None, alias="betrokkenSamenwerkingsverband"
    )
    betrokken_gorzen_en_aanwassen: NEN3610ID | None = Field(
        None, alias="betrokkenGorzenEnAanwassen"
    )
    is_gebaseerd_op: list[NEN3610ID] | None = Field(None, alias="isGebaseerdOp")
    van: NEN3610ID | None = None
    ten_name_van: NEN3610ID | None = Field(None, alias="tenNameVan")


class TypeDeelEnNummer(BaseModel):
    deel: str | None = None
    nummer: str | None = None
    reeks: Waardelijst | None = None
    registercode: Waardelijst | None = None
    soort_register: Waardelijst | None = Field(None, alias="soortRegister")


class TypeKadastraleAanduiding(BaseModel):
    appartementsrecht_volgnummer: int | None = Field(
        None, alias="appartementsrechtVolgnummer"
    )
    kadastrale_gemeente: Waardelijst | None = Field(None, alias="kadastraleGemeente")
    perceelnummer: int | None = None
    sectie: str | None = None


class TypeKoopsom(BaseModel):
    bedrag: Bedrag | None = None
    indicatie_meer_objecten: bool | None = Field(None, alias="indicatieMeerObjecten")
    koopjaar: int | None = None


class TypeLandinrichtingsrente(BaseModel):
    bedrag: Bedrag | None = None
    eindjaar: int | None = None


class TypeOppervlak(BaseModel):
    soort_grootte: Waardelijst | None = Field(None, alias="soortGrootte")
    waarde: float | None = None


class ZekerheidsstellingHypothecair(FieldZekerheidsstelling):
    pass


class ZekerheidsstellingInzakeBeslag(FieldZekerheidsstelling):
    aard: Waardelijst | None = None


class FieldOnroerendeZaak(FieldKadastraalObject):
    type: OnroerendeZaakTypeEnum | None = None
    aard_cultuur_bebouwd: Waardelijst | None = Field(None, alias="aardCultuurBebouwd")
    aard_cultuur_onbebouwd: Waardelijst | None = Field(
        None, alias="aardCultuurOnbebouwd"
    )
    heeft_meer_adressen: bool | None = Field(None, alias="heeftMeerAdressen")
    kadastrale_aanduiding: TypeKadastraleAanduiding | None = Field(
        None, alias="kadastraleAanduiding"
    )
    koopsom: TypeKoopsom | None = None
    landinrichtingsrente: list[TypeLandinrichtingsrente] | None = Field(
        None, min_items=0
    )
    toelichting_bewaarder: str | None = Field(None, alias="toelichtingBewaarder")
    ontstaan_uit_oz: list[OnroerendeZaakFiliatie] | None = Field(
        None, alias="ontstaanUitOZ", min_items=0
    )
    is_vermeld_in: list[NEN3610ID] | None = Field(
        None, alias="isVermeldIn", min_items=0
    )
    overgegaan_in: list[VoorwaartseOnroerendeZaakFiliatie] | None = Field(
        None, alias="overgegaanIn"
    )


class Appartementsrecht(FieldOnroerendeZaak):
    pass


class ATCollectie(BaseModel):
    adres_locaties: list[FieldAdresLocatie] | None = Field(None, alias="adresLocaties")
    gevraagd_gebied: GevraagdGebied | None = Field(None, alias="gevraagdGebied")
    locatie_kadastraal_objecten: list[LocatieKadastraalObject] | None = Field(
        None, alias="locatieKadastraalObjecten"
    )
    onroerende_zaken: list[FieldOnroerendeZaak] | None = Field(
        None, alias="onroerendeZaken"
    )


class Beperkingsgebied(BaseModel):
    identificatie: NEN3610ID | None = None
    ontleend_aan: list[ObjectReferentie] | None = Field(None, alias="ontleendAan")


class Collectie(BaseModel):
    aantekeningen: list[Aantekening] | None = None
    locatie_kadastraal_objecten: list[LocatieKadastraalObject] | None = Field(
        None, alias="locatieKadastraalObjecten"
    )
    onroerende_zaken: list[FieldOnroerendeZaak] | None = Field(
        None, alias="onroerendeZaken"
    )
    personen: list[FieldPersoon] | None = None
    adres_locaties: list[FieldAdresLocatie] | None = Field(None, alias="adresLocaties")
    attendering_kadastraal_objecten: None | (list[AttenderingKadastraalObject]) = Field(
        None, alias="attenderingKadastraalObjecten"
    )
    signalering_kadastraal_objecten: None | (list[SignaleringKadastraalObject]) = Field(
        None, alias="signaleringKadastraalObjecten"
    )
    stukdelen: list[Stukdeel] | None = None
    stukken: list[FieldStuk] | None = None
    verblijfsobjecten: list[Verblijfsobject] | None = None
    aanvullende_gegevens: list[AanvullendeGegevens] | None = Field(
        None, alias="aanvullendeGegevens"
    )


class Erfpachtcanon(BaseModel):
    einddatum_afkoop: datetime | None = Field(None, alias="einddatumAfkoop")
    identificatie: NEN3610ID | None = None
    indicatie_oude_onroerende_zaak_betrokken: bool | None = Field(
        None, alias="indicatieOudeOnroerendeZaakBetrokken"
    )
    jaarlijks_bedrag: JaarlijksBedrag | None = Field(None, alias="jaarlijksBedrag")
    soort: Waardelijst | None = None
    betreft: NEN3610ID | None = None
    is_gebaseerd_op: NEN3610ID | None = Field(None, alias="isGebaseerdOp")
    is_vermeld_in: list[NEN3610ID] | None = Field(
        None, alias="isVermeldIn", min_items=0
    )


class GeregistreerdPersoon(BaseModel):
    adellijke_titel_of_predikaat: Waardelijst | None = Field(
        None, alias="adellijkeTitelOfPredikaat"
    )
    bsn: str = Field(..., max_length=9, pattern="([0][0-9]{8})|([1-9][0-9]{7,8})")
    geboorte: Geboorte | None = None
    geslacht: Geslacht | None = None
    in_onderzoek: bool | None = Field(None, alias="inOnderzoek")
    naam: Naam | None = None
    overlijden: Overlijden | None = None


class HPICollectie(Collectie):
    zekerheidsstellingen: list[FieldZekerheidsstelling] | None = None
    overig_betrokken_kadastraal_objecten: None | (
        list[OverigBetrokkenKadastraalObject]
    ) = Field(None, alias="overigBetrokkenKadastraalObjecten")


class HypotheekinformatieProduct(Product):
    met: HPICollectie | None = None


class Kadasterstuk(FieldStuk):
    portefeuillenummer: PortefeuilleId | None = None


class Leidingnetwerk(FieldOnroerendeZaak):
    aard: Waardelijst | None = None
    omschrijving: str | None = None


class NatuurlijkPersoon(FieldPersoon):
    indicatie_overleden: bool | None = Field(None, alias="indicatieOverleden")
    betreft: GeregistreerdPersoon | None = None


class OLPCollectie(BaseModel):
    aanvullende_gegevens: list[AanvullendeGegevens] | None = Field(
        None, alias="aanvullendeGegevens"
    )
    adres_locaties: list[FieldAdresLocatie] | None = Field(None, alias="adresLocaties")
    locatie_kadastraal_objecten: list[LocatieKadastraalObject] | None = Field(
        None, alias="locatieKadastraalObjecten"
    )
    onroerende_zaken: list[FieldOnroerendeZaak] | None = Field(
        None, alias="onroerendeZaken"
    )
    personen: list[FieldPersoon] | None = None


class ObjectlijstPersoonProduct(Product):
    met: OLPCollectie | None = None


class OICollectie(BaseModel):
    adres_locaties: list[FieldAdresLocatie] | None = Field(None, alias="adresLocaties")
    locatie_kadastraal_objecten: list[LocatieKadastraalObject] | None = Field(
        None, alias="locatieKadastraalObjecten"
    )
    onroerende_zaken: list[FieldOnroerendeZaak] | None = Field(
        None, alias="onroerendeZaken"
    )


class OvergegaanInProduct(Product):
    met: OICollectie | None = None


class Perceel(FieldOnroerendeZaak):
    kadastrale_grootte: TypeOppervlak | None = Field(None, alias="kadastraleGrootte")
    indicatie_meettarief_verschuldigd: bool | None = Field(
        None, alias="indicatieMeettariefVerschuldigd"
    )
    plaatscoordinaten: PointGeoJSON | None = None


class PTCollectie(BaseModel):
    adres_locaties: list[FieldAdresLocatie] | None = Field(None, alias="adresLocaties")
    gevraagd_gebied: GevraagdGebied | None = Field(None, alias="gevraagdGebied")
    locatie_kadastraal_objecten: list[LocatieKadastraalObject] | None = Field(
        None, alias="locatieKadastraalObjecten"
    )
    onroerende_zaken: list[FieldOnroerendeZaak] | None = Field(
        None, alias="onroerendeZaken"
    )


class TerInschrijvingAangebodenStuk(FieldStuk):
    aard: Waardelijst | None = None
    deel_en_nummer: TypeDeelEnNummer | None = Field(None, alias="deelEnNummer")
    heeft_kadaster_verzoek: bool | None = Field(None, alias="heeftKadasterVerzoek")
    status_stuk_or: Waardelijst | None = Field(None, alias="statusStukOR")
    tekening_ingeschreven: bool | None = Field(None, alias="tekeningIngeschreven")
    tijdstip_aanbieding: Tijdstip | None = Field(None, alias="tijdstipAanbieding")
    tijdstip_ondertekening: Tijdstip | None = Field(None, alias="tijdstipOndertekening")


class AdresTreffersProduct(Product):
    met: ATCollectie | None = None


class EDICollectie(Collectie):
    erfpachtcanons: list[Erfpachtcanon] | None = None
    gezamenlijk_aandelen: list[GezamenlijkAandeel] | None = Field(
        None, alias="gezamenlijkAandelen"
    )
    mandeligheden: list[Mandeligheid] | None = None
    tenaamstellingen: list[Tenaamstelling] | None = None
    appartementsrecht_splitsingen: list[AppartementsrechtSplitsing] | None = Field(
        None, alias="appartementsrechtSplitsingen"
    )
    publiekrechtelijke_beperkingen: list[PubliekrechtelijkeBeperking] | None = Field(
        None, alias="publiekrechtelijkeBeperkingen"
    )
    beperkingsgebieden: list[Beperkingsgebied] | None = None
    zakelijk_rechten: list[ZakelijkRecht] | None = Field(None, alias="zakelijkRechten")
    verkavel_objecten: list[VerkavelObject] | None = Field(
        None, alias="verkavelObjecten"
    )
    herverkavelingsgebieden: list[Herverkavelingsgebied] | None = None


class EGICollectie(Collectie):
    erfpachtcanons: list[Erfpachtcanon] | None = None
    gezamenlijk_aandelen: list[GezamenlijkAandeel] | None = Field(
        None, alias="gezamenlijkAandelen"
    )
    mandeligheden: list[Mandeligheid] | None = None
    tenaamstellingen: list[Tenaamstelling] | None = None
    appartementsrecht_splitsingen: list[AppartementsrechtSplitsing] | None = Field(
        None, alias="appartementsrechtSplitsingen"
    )
    publiekrechtelijke_beperkingen: list[PubliekrechtelijkeBeperking] | None = Field(
        None, alias="publiekrechtelijkeBeperkingen"
    )
    beperkingsgebieden: list[Beperkingsgebied] | None = None
    zakelijk_rechten: list[ZakelijkRecht] | None = Field(None, alias="zakelijkRechten")
    attendering_personen: list[AttenderingPersoon] | None = Field(
        None, alias="attenderingPersonen"
    )
    signalering_personen: list[SignaleringPersoon] | None = Field(
        None, alias="signaleringPersonen"
    )
    verkavel_objecten: list[VerkavelObject] | None = Field(
        None, alias="verkavelObjecten"
    )
    herverkavelingsgebieden: list[Herverkavelingsgebied] | None = None


class EigenaarsinformatieProduct(Product):
    met: EGICollectie | None = None


class EigendomsinformatieProduct(Product):
    met: EDICollectie | None = None


class GeleverdProductEigenaarsinformatie(BaseModel):
    negatieve_mededeling: NegatieveMededelingProduct | None = Field(
        None, alias="negatieveMededeling"
    )
    product: EigenaarsinformatieProduct | None = None
    pdf: str | None = None


class GeleverdProductObjectlijstPersoon(BaseModel):
    negatieve_mededeling: NegatieveMededelingProduct | None = Field(
        None, alias="negatieveMededeling"
    )
    product: ObjectlijstPersoonProduct | None = None
    pdf: str | None = None


class ObjectlijstPersoon(BaseModel):
    proces: ProcesVerwerking | None = None
    product_gegevens: ProductGegevens | None = Field(None, alias="productGegevens")
    geleverd_product: GeleverdProductObjectlijstPersoon | None = Field(
        None, alias="geleverdProduct"
    )


class PostcodeTreffersProduct(Product):
    met: PTCollectie | None = None


class Eigenaarsinformatie(BaseModel):
    proces: ProcesVerwerking | None = None
    product_gegevens: ProductGegevens | None = Field(None, alias="productGegevens")
    geleverd_product: GeleverdProductEigenaarsinformatie | None = Field(
        None, alias="geleverdProduct"
    )


class GeleverdProductEigendomsinformatie(BaseModel):
    product: EigendomsinformatieProduct | None = None
    pdf: str | None = None
    postcode_treffers: PostcodeTreffersProduct | None = Field(
        None, alias="postcodeTreffers"
    )
    overgegaan_in: OvergegaanInProduct | None = Field(None, alias="overgegaanIn")
    adres_treffers: AdresTreffersProduct | None = Field(None, alias="adresTreffers")


class GeleverdProductHypotheekinformatie(BaseModel):
    product: HypotheekinformatieProduct | None = None
    pdf: str | None = None
    postcode_treffers: PostcodeTreffersProduct | None = Field(
        None, alias="postcodeTreffers"
    )
    overgegaan_in: OvergegaanInProduct | None = Field(None, alias="overgegaanIn")
    adres_treffers: AdresTreffersProduct | None = Field(None, alias="adresTreffers")


class GeleverdProductKadastraleKaart(BaseModel):
    pdf: str | None = None
    postcode_treffers: PostcodeTreffersProduct | None = Field(
        None, alias="postcodeTreffers"
    )
    overgegaan_in: OvergegaanInProduct | None = Field(None, alias="overgegaanIn")
    adres_treffers: AdresTreffersProduct | None = Field(None, alias="adresTreffers")


class Hypotheekinformatie(BaseModel):
    proces: ProcesVerwerking | None = None
    product_gegevens: ProductGegevens | None = Field(None, alias="productGegevens")
    geleverd_product: GeleverdProductHypotheekinformatie | None = Field(
        None, alias="geleverdProduct"
    )


class KadastraleKaart(BaseModel):
    proces: ProcesVerwerking | None = None
    product_gegevens: ProductGegevens | None = Field(None, alias="productGegevens")
    geleverd_product: GeleverdProductKadastraleKaart | None = Field(
        None, alias="geleverdProduct"
    )


class Eigendomsinformatie(BaseModel):
    proces: ProcesVerwerking | None = None
    product_gegevens: ProductGegevens | None = Field(None, alias="productGegevens")
    geleverd_product: GeleverdProductEigendomsinformatie | None = Field(
        None, alias="geleverdProduct"
    )
